### ISSUE TITLE
cannot send connect message of stomp protocol correctly 

### ISSUE THREAD

**Issue by julieyuan** [Fyro-Ing/JMeter-WebSocket-StompSampler#1]
Hi,
Thank you for developing this pludgin so that I can use Jmeter to test websocket stomp protocol. 

I met a issue with this pludgin to test websocket stomp petrol with Jmeter. I am not sure what the real reason is. 

Here are my Test Thread: 

![test thread](https://cloud.githubusercontent.com/assets/4251563/16264174/9227e306-38aa-11e6-91aa-b35e91e3cb6b.png)

Jmeter's result:
![test result](https://cloud.githubusercontent.com/assets/4251563/16264223/d355c3f2-38aa-11e6-9514-c6ce1a9c8ec6.png)

![screen shot 2016-06-22 at 6 55 10 pm](https://cloud.githubusercontent.com/assets/4251563/16264231/df8e2a24-38aa-11e6-97ef-7fdb0287b620.png)

Jmeter said "the connect message is empty" and the request message said: ["CONNECT\n\n\u0000"]

I don't know why Jmeter cannot send the conncet message to the server correctly. Please help me to take a look. 

Thanks again.

**Comment by Fyro-Ing** [comment]
Use '\n' like this (in one line)

Connect Message :

CONNECT\naccept-version:1.1,1.0\nheart-beat:10000,10000

Subscribe : 

SUBSCRIBE\nid:sub-${counter}\ndestination:/topic/{my-topic}

**Comment by julieyuan** [comment]
Thank you so much @Fyro-Ing. I tried with your method but it failed again. 
![screen shot 2016-06-27 at 6 01 09 pm](https://cloud.githubusercontent.com/assets/4251563/16376090/342fcab2-3c91-11e6-9c7e-90f64bcfed1d.png)
![screen shot 2016-06-27 at 5 55 39 pm](https://cloud.githubusercontent.com/assets/4251563/16375915/6614e194-3c90-11e6-94eb-f807947f3564.png)

I didn't fill the subscribe message in the test scripture because I can get the session Id only after successful connection.  The session Id is random allocated by the server. 
![screen shot 2016-06-27 at 5 58 29 pm](https://cloud.githubusercontent.com/assets/4251563/16375992/c9c3ccf0-3c90-11e6-8b5c-57df7b42ec9c.png)

Is there any other field do I need to fill in ?

**Comment by Fyro-Ing** [comment]
In my use case, i use Sockjs protocol whith Stomp where process is :
-> send GET '/info' to my websocket endpoint
-> ws(s)://{websocket-endpoint}/{counter}/{connect-id}/{protocol}
where :
* counter is an incremented number
* connect-id is a random string on 8 characters
* protocol is one of 3 protocols (websocket, xhr-streaming, xhr-polling)

sample :

![sockjs-stomp](https://cloud.githubusercontent.com/assets/12964258/16415563/2e7277c0-3d3e-11e6-9c7a-702d13666446.png)


what is your client and server protocols ? sockjs, an other ?

**Comment by julieyuan** [comment]
Hi Fyro-lng, thank you for your answer. 

In my case, client and server protocols are also sockjs with stomp. Here are the related code:
![2016-7-5 14-32-25](https://cloud.githubusercontent.com/assets/4251563/16575871/0d1a1f76-42be-11e6-85ee-b308b4a86bac.png)

**Comment by julieyuan** [comment]
Hi Fyro-lng,  Thank you for your answers.  In my case, we also use sockjs with stomp protocols. Dev just changed related code recently. 
![screen shot 2016-07-05 at 3 58 19 pm](https://cloud.githubusercontent.com/assets/4251563/16577798/d3ed8970-42c9-11e6-9389-10acad7fd1c4.png)

**Comment by Fyro-Ing** [comment]
pre-release 0.3.0-alpha without subscription to test connection step

 https://github.com/Fyro-Ing/JMeter-WebSocket-StompSampler/releases/tag/0.3.0-alpha

**Comment by julieyuan** [comment]
Thanks very much:) I will try it

**Comment by sudheermaddukuri** [comment]
@Fyro-Ing Where Can I find your jmx file? Need to take a look at ${counter} and ${connectionId} generation logic? Can these variables be random?

**Comment by Fyro-Ing** [comment]
${connectionId} is a random string : ${__RandomString(8,abcdefghijklmnopqrstuvwxyz,sessionId)};
${counter} is a jmeter counter

to verify if the messages reach the subscribers, modify "Subscribe pattern" on Jmeter with the message pattern expected.
in my use case, it was a\[\"Message\ndestination:${topic-destination} to test first part pattern, without the complete content

**Comment by Amarchetan** [comment]
<img width="1143" alt="screen shot 2018-03-24 at 12 23 45 pm" src="https://user-images.githubusercontent.com/6037587/37868166-ad28de00-2f5f-11e8-90a1-e20fc8d40866.png">
<img width="1144" alt="screen shot 2018-03-24 at 12 24 01 pm" src="https://user-images.githubusercontent.com/6037587/37868168-b36366d2-2f5f-11e8-992c-f75677035499.png">
<img width="901" alt="screen shot 2018-03-24 at 12 25 06 pm" src="https://user-images.githubusercontent.com/6037587/37868171-bfea7c10-2f5f-11e8-87e3-5d5d73da4009.png">
<img width="903" alt="screen shot 2018-03-24 at 12 25 26 pm" src="https://user-images.githubusercontent.com/6037587/37868172-c4fb6354-2f5f-11e8-8158-c26de0aeda77.png">
<img width="919" alt="screen shot 2018-03-24 at 12 25 36 pm" src="https://user-images.githubusercontent.com/6037587/37868174-c7430108-2f5f-11e8-8bff-c4253828e2db.png">

Hi,
Thank you for developing this plugin.
I am new to Websocket/STOMP and trying to send a message to a Web-socket Stomp endpoint via Jmeter.
Please find attached the screenshots of the sample result, request and response data.

I am trying with frame CONNECT and SUBSCRIBE message patterns as mentioned above.
Is there a way to SEND a message to the stomp endpoint using this plugin via Jmeter?
or Am I missing something?

Appeciate all the help.

Thanks

**Comment by ngamage** [comment]
@julieyuan can you please share the WebSocket sampler you used?

**Comment by sourabh24** [comment]
Hello Expertise, 
I configured websocket for STOMP protocol, but I didnt get the response from server, Screenshot attached for reference. 

Thanks in advance. 
![STOMP_REQUEST](https://user-images.githubusercontent.com/4804735/60016926-32f1fa00-96a5-11e9-9542-7528606d7a43.JPG)
![STOMP_RESPONSE](https://user-images.githubusercontent.com/4804735/60016929-338a9080-96a5-11e9-89a0-0cd4c06839a9.JPG)
![STOMP_RESPONSE-Message](https://user-images.githubusercontent.com/4804735/60016930-338a9080-96a5-11e9-989a-256686628a5f.JPG)
![STOMP-Response](https://user-images.githubusercontent.com/4804735/60016932-34232700-96a5-11e9-9911-d19fceee57bd.JPG)
